# Generated by Django 4.2 on 2023-06-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_message', '0002_initial'),
        ('app_client', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(blank=True, choices=[('F', 'Завершена'), ('C', 'Создана'), ('S', 'Запущена')], max_length=1, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_date', models.DateField(verbose_name='Дата завершения рассылки')),
                ('finish_time', models.TimeField(verbose_name='Время завершения рассылки')),
                ('clients', models.ManyToManyField(related_name='newsletters', to='app_client.client', verbose_name='Клиенты')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Создана')),
                ('messages', models.ManyToManyField(related_name='newsletters', to='app_message.message', verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], max_length=1, verbose_name='Статус')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_client.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_message.message', verbose_name='Сообщение')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_newsletter.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог отправки письма',
                'verbose_name_plural': 'Логи отправок писем',
                'db_table': 'newsletter_logs',
            },
        ),
    ]
