# Generated by Django 4.2 on 2023-06-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlog',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_newsletter.newsletter', verbose_name='Рассылка'),
        ),
    ]
